### ISSUE TITLE
Support individual cell rotation

### ISSUE THREAD

**Issue by xaqbr** [DarkKilauea/godot-scene-map#1]
Could you add support for individual cell rotation like in GridMap? I can sort of work around this by editing the children's transforms manually, but they all get reset any time I add a new item to the scene palette.

**Comment by DarkKilauea** [comment]
Yea, I think that makes sense.  I'd like to get to feature parity with GridMap so this addon can be used as a replacement.

**Comment by DarkKilauea** [comment]
I added support for rotating cells in the main branch.

If you'd like to take a look and give feedback, please follow the instructions to manually install the addon in the README, then leave feedback in this issue.  I plan to spend some more time tweaking the workflow before publishing an update to the Asset Library.

Thanks.

**Comment by DarkKilauea** [comment]
Released to Asset Library in version 0.6
